### ISSUE TITLE
attack/main.py 

### ISSUE THREAD

**Issue by DENGhy123** [MiracleHH/RecommPoison#4]
In attack/main.py, line 150"filler_items=[]", filler_items is an empty list, in line 153 "for i,items in enumerate(filler_items):". I think this circulation is meaningless, because  "filler_items" is empty. So, could you please explain it? Thank you very much.

**Comment by DENGhy123** [comment]
@MiracleHH

**Comment by MiracleHH** [comment]
Hi @DENGhy123 , thanks for your interest in our work!
As mentioned in [Line 149](https://github.com/MiracleHH/RecommPoison/blob/main/attacks/main.py#L149), you can load external data for the filler items near [Line 150](https://github.com/MiracleHH/RecommPoison/blob/main/attacks/main.py#L150), then [Line 153-168](https://github.com/MiracleHH/RecommPoison/blob/main/attacks/main.py#L153-L168) will make sense. If you have no existing filler items data to load, then there would be no operations executed for [Line 153-168](https://github.com/MiracleHH/RecommPoison/blob/main/attacks/main.py#L153-L168), and it's okay to simply ignore this part. The major concern here is that this attack process is usually time-consuming, and we can speed up the attack process by **re-using** previously generated filler items. For instance, if you have already generated the filler items for 0.5% fake users, you can start from these existing filler items (i.e., add these filler times in [Line 150](https://github.com/MiracleHH/RecommPoison/blob/main/attacks/main.py#L150)) to generate **additional 0.5%** fake users such that you could get the evaluation results for **overall 1%** fake users much faster.

**Comment by DENGhy123** [comment]
okay, get it. Thank you very much for your response. By the way, I want to collect all the poisoned data and save it in the format of "train.csv". What should I do? In the codes, there are a lot of variates like target_users, mornal_user, unrated_items, candidate_users, candidate_items, ratings and _ratings. I am confused. Could you please kindly help me to write some codes? Thank you so much! @MiracleHH

**Comment by MiracleHH** [comment]
@DENGhy123 Currently all poisoned items will be stored in a `TXT` file (see [Line 299-300](https://github.com/MiracleHH/RecommPoison/blob/main/attacks/main.py#L299-L300)). I write a toy example for you as follows.

```Python
import pandas as pd

FAKE_PATH = './poison/fake_record.csv'


fake_users, fake_items, fake_labels = [], [], []

for i, items in enumerate(filler_items):
	fake_users.extend([num_uers + i] * len(items))
	fake_items.extend(items)
	fake_labels.extend([1.0] * len(items))

fake_dict = {'userId': fake_users, 'itemId': fake_items, 'rating': fake_labels}
fake_df = pd.DataFrame(fake_dict)

fake_df.to_csv(FAKE_PATH, index = None)

```

Note that, here the stored rating scores in `fake_record.csv` are all **implicit** ones (i.e., 1.0 or 0.0). You can also define your own rules to generate **explicit** rating scores for each filler item. For instance, we can generate rating scores for each filler item according to their previous fitted normal distributions to ensure their scores are much similar to other normal ratings. The example code is shown below (note the difference when generating `fake_labels`).

```Python
import numpy as np
from scipy import stats

# Generate a new explicit rating score 
def generate_rating(ratings, low = 1, high = 5):
	# Fitting distribution to get mean and standard deviation
	mean, std = stats.norm.fit(ratings)
	t=round(np.random.normal(loc = mean, scale = std, size = 1)[0])

	if t < low:
		t = low
	elif t > high:
		t = high
	return t

fake_users, fake_items, fake_labels = [], [], []

for i, items in enumerate(filler_items):
	fake_users.extend([num_uers + i] * len(items))
	fake_items.extend(items)

	temp = [generate_rating(np.array(item_ratings[j])) for j in items]
	# Assign the target item with the highest score if you like
	temp[-1] = 5
	fake_labels.extend(temp)

```

Here `item_ratings` is a list containing the rating records for each item in the training dataset.

Hope this is helpful to you. Thanks!

**Comment by DENGhy123** [comment]
@MiracleHH Thank you very much. You are so nice! Your code is really helpful to me.
